### PR TITLE
List devices command and quiet option

### PR DESCRIPTION
**Pull request by jacksonh**
Let me know if either of these features interest you, I can separate them out if you'd like.

--list-devices is a new command that simply lists the connected devices to stdout. I am using this in my CI setup, basically to run instruments on each device.

--quiet suppresses most output and is just needed so I can parse the output of --list-devices.

### CODE REVIEW

**Comment by jacksonh** [comment]
I'll leave this open for now, but I've also decided to add uninstall support, so I think I'll refactor things a little to have commands and options:

fruitstap install [-i/--id device_id]  -b/--bundle bundle.app [-a/--args arguments]
fruitstrap uninstall [-i/--id device_id]  -b/--bundle bundle-identifier
fruitstrap list-devices

and: [-q/--quiet]  [-t/--timeout]  as global options.

**Comment by tcoulter** [comment]
Love uninstall. Just what I was looking for.

**Comment by btaylor-litl** [comment]
Jackson, can you merge in https://github.com/btaylor-litl/fruitstrap/commit/a011a01c89884a39aab75994879ee4809858643a from me?  It adds back support for the device_id parameter which got lost in 3b37a33.

Thanks for the uninstall code, btw!

**Comment by kuzm2000** [comment]
Confirming, only 'list-devices' is working (but hanging after listing deices), nothing else

**Comment by 10p-freddo** [comment]
Thanks for the pull request. Unfortunately, I'm not able to maintain the project any more. I'd encourage you to submit this request to one of the forks, or maintain your own fork. Cheers!

**Pull request closed without merging**
